version: "2.1"

orbs:
  python: circleci/python@3.0.0
  codecov: codecov/codecov@5.0.3
  github-utils: trustedshops-public/github-utils@1.1.2
  semantic-release: trustedshops-public/semantic-release@6.0.0

executors:
  node:
    docker:
      - image: cimg/python:3.12-node
  python-linux:
    docker:
      - image: cimg/python:3.12

jobs:
  build-gh-pages-demo:
    executor: node
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
          args: --all-extras
      - run:
          name: Build html documentation
          command: |
            cd demo
            poetry run mkdocs build
      - github-utils/publish_github_pages:
          folder: demo/site
          git_commit_author_email: "no-reply@timo-reymann.de"
          git_commit_author_name: "CircleCI"
  pip-publish:
    executor: python-linux
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
          args: --all-extras
      - run:
          name: Publish package
          command: |
            poetry publish \
              --build \
              --username "$TWINE_USERNAME" \
              --password "$TWINE_PASSWORD"
workflows:
  main:
    jobs:
      - build-gh-pages-demo:
          filters:
            branches:
              only:
                - main
      - pip-publish:
          name: publish-pypi
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - semantic-release/with_existing_config:
          name: semantic-release
          additional_packages: "@google/semantic-release-replace-plugin"
          requires:
            - integration-test-win
            - integration-test-macos
            - integration-test-linux
          filters:
            branches:
              only:
                - main