site_name: Demo docs
theme: material
plugins:
  - decision-records:
      decisions_folder: adr
      ticket_url_prefix: https://google.com/
      lifecycle_stages: { }
      required_deciders_count: 0
nav:
  - index.md
  - Architecture Decision Records:
      - adr/000-TEMPLATE.md
      - adr/001.md
      - adr/002-Solution-for-preview.md
